program inlineasm;

(* 
   R10 is used as stack pointer and points to a reference to the the return
   value.  Parameters a and b are at the following words.
   Registers 0, 8, 12 - 15 may be freely used.
   
   Note: The return sequence is generated by the compiler to
   include bank switching code when necessary.
*)   

var
    c: integer;

function add (a, b: integer): integer; assembler;
    mov  *r10, r12              // get pointer to return value
    mov  @a, *r12
    a    @b, *r12
end;

procedure setC (a: integer); assembler;
    mov @a, @c			// access global variable
end;

begin
    c := 2;
    writeln ('5 + 7 = ', add (5, 7));
    setC (9);
    writeln ('c = ', c);
    waitkey
end.
