program inlineasm;

(* 
   R10 is used as stack pointer and points to a reference to the the return
   value.  Parameters a and b are at the following words.
   Registers 0, 8, 12 - 15 may be freely used.
   
   Note: The return sequence is generated by the compiler to
   include bank switching code when necessary.
*)   


function add (a, b: integer): integer; assembler;
    mov  *r10, r12              // get pointer to return value
    mov  @2(r10), *r12
    a    @4(r10), *r12
end;

begin
    writeln ('5 + 7 = ', add (5, 7));
    waitkey
end.
