program inlineasm;

(* 
   R10 is used as stack pointer and points to a reference to the the return
   value.  Parameters a and b are at the following words.
   
   Note: The return sequence will soon be generated by the compiler to
   include bank switching code, meaning R10 must not be modified.  Therefore
   auto increment is not used when accessing R10 in this example.
*)   


function add (a, b: integer): integer; assembler;
    mov *r10, r12		// get pointer to return value
    mov @2(r10), *r12
    a @4(r10), *r12
    
    ai r10, 8			// remove parameters from stack (including return page number at R10 + 6)
    b *r11
end;

begin
    writeln ('5 + 7 = ', add (5, 7));
    waitkey
end.
